<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "user".
 *
 * @property integer $id
 * @property string $nombre
 * @property string $apellido
 * @property string $nro_documento
 * @property string $fecha_nacimiento
 * @property string $email
 * @property string $aliasModel
 */
abstract class User extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'apellido', 'nro_documento', 'email'], 'required'],
            [['fecha_nacimiento'], 'safe'],
            [['nombre', 'apellido', 'nro_documento', 'email'], 'string', 'max' => 200]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'apellido' => 'Apellido',
            'nro_documento' => 'Nro Documento',
            'fecha_nacimiento' => 'Fecha Nacimiento',
            'email' => 'Email',
        ];
    }




}
